server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    inetutils:
      preferred-networks: 192.168.1.104
      ignored-interfaces:
        - lo
        - vEthernet (Default Switch)
        - vEthernet (nat)

logging:
  level:
    # 设置 gateway 日志级别
    org.springframework.cloud.gateway: debug