server:
  port: 10080
management:
  server:
    port: 10081
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: consumer-server
  cloud:
    inetutils:
      preferred-networks: 192.168.1.104
      ignored-interfaces:
        - lo
        - vEthernet (Default Switch)
        - vEthernet (nat)
